import { BaseEntity, Entity, PrimaryGeneratedColumn, Column, ManyToOne } from 'typeorm';

import { TaskStatus } from './task-status.enum';
import { User } from 'src/auth/user.entity';

@Entity()
export class Task extends BaseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  title: string;

  @Column()
  description: string;

  @Column()
  status: TaskStatus;

  // this defines the relationship, but not the column itself
  @ManyToOne(type => User, user => user.tasks, { eager: false }) // will save the primary key (id) of the user on the task
  user: User;
  // and this defines the column which is btw automatically generated by TypeORM
  @Column()
  userId: number;
}
