/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PkSpinner {}
  interface PkStockFinder {}
  interface PkStockPrice {
    'stockSymbol': string;
  }
}

declare global {


  interface HTMLPkSpinnerElement extends Components.PkSpinner, HTMLStencilElement {}
  var HTMLPkSpinnerElement: {
    prototype: HTMLPkSpinnerElement;
    new (): HTMLPkSpinnerElement;
  };

  interface HTMLPkStockFinderElement extends Components.PkStockFinder, HTMLStencilElement {}
  var HTMLPkStockFinderElement: {
    prototype: HTMLPkStockFinderElement;
    new (): HTMLPkStockFinderElement;
  };

  interface HTMLPkStockPriceElement extends Components.PkStockPrice, HTMLStencilElement {}
  var HTMLPkStockPriceElement: {
    prototype: HTMLPkStockPriceElement;
    new (): HTMLPkStockPriceElement;
  };
  interface HTMLElementTagNameMap {
    'pk-spinner': HTMLPkSpinnerElement;
    'pk-stock-finder': HTMLPkStockFinderElement;
    'pk-stock-price': HTMLPkStockPriceElement;
  }
}

declare namespace LocalJSX {
  interface PkSpinner {}
  interface PkStockFinder {
    'onPkSymbolSelected'?: (event: CustomEvent<string>) => void;
  }
  interface PkStockPrice {
    'stockSymbol'?: string;
  }

  interface IntrinsicElements {
    'pk-spinner': PkSpinner;
    'pk-stock-finder': PkStockFinder;
    'pk-stock-price': PkStockPrice;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pk-spinner': LocalJSX.PkSpinner & JSXBase.HTMLAttributes<HTMLPkSpinnerElement>;
      'pk-stock-finder': LocalJSX.PkStockFinder & JSXBase.HTMLAttributes<HTMLPkStockFinderElement>;
      'pk-stock-price': LocalJSX.PkStockPrice & JSXBase.HTMLAttributes<HTMLPkStockPriceElement>;
    }
  }
}


